### ISSUE TITLE
为你这个登录页面的背景点赞！

### ISSUE THREAD

**Issue by twhy** [hunger13/Test#1]
改进建议
1. 可以给你的 input 设置 `box-sizing: border-box`
2. 注册 登录链接 下边那个下边框要放离文字远一点点，比如设置 `padding: 5px`，虽然知乎不是通过下边框做的。

**Comment by hunger13** [comment]
已经修改,tab栏切换登录和注册因为我们还没有学习js,所以暂时先不做了,谢谢老师~
